CREATE TABLE events (
  id SERIAL PRIMARY KEY,
  code VARCHAR(10) UNIQUE NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  date TIMESTAMP WITH TIME ZONE,
  location VARCHAR(255),
  creator_id VARCHAR(255) NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
